#!/usr/bin/env bash
#
# Bifrost installer / updater.
#
# Installs the runtimes Bifrost needs (node >= 22 and bun) if they are missing,
# clones the CLI into a stable location, builds it with Bun, and links a
# `bifrost` command onto your PATH. Re-running it (or `bifrost update`) pulls the
# latest commit and rebuilds.
#
# This script is published to the PUBLIC bootstrap repo (callmedraxx/bifrost),
# so the curl|bash link needs no token to fetch. The CLI source repo
# (callmedraxx/bifrost-code) stays PRIVATE, so cloning it needs a GitHub
# credential — pass one of:
#
#   # 1) GitHub PAT (repo read) — true one-liner on a bare machine:
#   GITHUB_TOKEN=ghp_xxx bash -c "$(curl -fsSL \
#     https://raw.githubusercontent.com/callmedraxx/bifrost/main/install.sh)"
#
#   # 2) SSH key already on the machine's GitHub account:
#   curl -fsSL https://raw.githubusercontent.com/callmedraxx/bifrost/main/install.sh \
#     | USE_SSH=1 bash
#
#   # 3) gh CLI already authenticated (gh auth setup-git):
#   curl -fsSL https://raw.githubusercontent.com/callmedraxx/bifrost/main/install.sh | bash
#
# After install, update any time with:   bifrost update
#
# Overrides (env vars):
#   BIFROST_REPO   repo slug (default: callmedraxx/bifrost-code)
#   BIFROST_REF    branch/tag/commit to track (default: main)
#   BIFROST_HOME   where the source is cloned (default: ~/.local/share/bifrost)
#   BIFROST_BIN_DIR  where the `bifrost` launcher is linked (default: ~/.local/bin)
#   GITHUB_TOKEN   token baked into the clone URL so future `bifrost update`s work
#   USE_SSH=1      clone over ssh (git@github.com:...) instead of https
#
set -euo pipefail

REPO="${BIFROST_REPO:-callmedraxx/bifrost-code}"
REF="${BIFROST_REF:-main}"
APP_DIR="${BIFROST_HOME:-$HOME/.local/share/bifrost}"
BIN_DIR="${BIFROST_BIN_DIR:-$HOME/.local/bin}"
NODE_MAJOR_MIN=22

log()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarn:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

have() { command -v "$1" >/dev/null 2>&1; }

node_major() {
  have node || return 1
  node -p 'process.versions.node.split(".")[0]' 2>/dev/null || return 1
}

ensure_node() {
  local major
  if major="$(node_major)" && [ "${major:-0}" -ge "$NODE_MAJOR_MIN" ]; then
    log "node $(node --version) already present"
    return
  fi
  if have node; then
    warn "node $(node --version) is older than v${NODE_MAJOR_MIN}; installing a newer one via nvm"
  else
    log "node not found; installing via nvm (no root required)"
  fi

  export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
  if [ ! -s "$NVM_DIR/nvm.sh" ]; then
    curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
  fi
  # shellcheck disable=SC1091
  . "$NVM_DIR/nvm.sh"
  nvm install "$NODE_MAJOR_MIN"
  nvm use "$NODE_MAJOR_MIN"
  nvm alias default "$NODE_MAJOR_MIN" >/dev/null 2>&1 || true
  have node || die "node install failed"
  log "node $(node --version) ready"
}

ensure_bun() {
  if have bun; then
    log "bun $(bun --version) already present"
    return
  fi
  log "bun not found; installing"
  curl -fsSL https://bun.sh/install | bash
  export BUN_INSTALL="${BUN_INSTALL:-$HOME/.bun}"
  export PATH="$BUN_INSTALL/bin:$PATH"
  have bun || die "bun install failed (open a new shell and re-run, or add \$HOME/.bun/bin to PATH)"
  log "bun $(bun --version) ready"
}

clone_url() {
  if [ "${USE_SSH:-0}" = "1" ]; then
    printf 'git@github.com:%s.git' "$REPO"
  elif [ -n "${GITHUB_TOKEN:-}" ]; then
    printf 'https://%s@github.com/%s.git' "$GITHUB_TOKEN" "$REPO"
  else
    printf 'https://github.com/%s.git' "$REPO"
  fi
}

sync_source() {
  local url; url="$(clone_url)"
  if [ -d "$APP_DIR/.git" ]; then
    log "updating source in $APP_DIR (ref: $REF)"
    git -C "$APP_DIR" remote set-url origin "$url"
    git -C "$APP_DIR" fetch --prune origin "$REF"
    git -C "$APP_DIR" checkout -f "$REF" 2>/dev/null || git -C "$APP_DIR" checkout -fB "$REF" FETCH_HEAD
    # Fast-forward to the fetched tip; reset is safe because the source tree is
    # build output we own, not user edits.
    git -C "$APP_DIR" reset --hard FETCH_HEAD
  else
    log "cloning $REPO into $APP_DIR (ref: $REF)"
    mkdir -p "$(dirname "$APP_DIR")"
    git clone "$url" "$APP_DIR"
    git -C "$APP_DIR" checkout -f "$REF"
  fi
}

build_cli() {
  log "installing dependencies (bun)"
  ( cd "$APP_DIR" && bun install )
  log "building"
  ( cd "$APP_DIR" && bun run build )
}

link_launcher() {
  mkdir -p "$BIN_DIR"
  local launcher="$BIN_DIR/bifrost"
  cat > "$launcher" <<EOF
#!/usr/bin/env bash
# Bifrost launcher (generated by install.sh).
set -euo pipefail
APP_DIR="$APP_DIR"
if [ "\${1:-}" = "update" ]; then
  exec bash "\$APP_DIR/scripts/install.sh" "\${@:2}"
fi
exec "\$APP_DIR/bin/bifrost" "\$@"
EOF
  chmod +x "$launcher"
  log "linked launcher: $launcher"
}

main() {
  have curl || die "curl is required; install it and re-run"
  have git  || die "git is required; install it and re-run"

  ensure_bun
  ensure_node
  sync_source
  build_cli
  link_launcher

  local version
  version="$("$APP_DIR/bin/bifrost" --version 2>/dev/null || true)"
  log "done — bifrost ${version:-installed}"

  case ":$PATH:" in
    *":$BIN_DIR:"*) printf '\nRun: \033[1mbifrost\033[0m   (update later with: bifrost update)\n' ;;
    *) warn "$BIN_DIR is not on your PATH. Add it, e.g.:"
       printf '  echo '\''export PATH="%s:$PATH"'\'' >> ~/.bashrc && exec bash\n' "$BIN_DIR"
       printf 'Then run: bifrost   (update later with: bifrost update)\n' ;;
  esac
}

main "$@"
